### ISSUE TITLE
Update details in the kebab menu

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/zairza-website#10]
## Description
Currently there are some incorrect information in the kebab menu in the mobile view of the website.
![Screenshot_2019-10-05 Zairza](https://user-images.githubusercontent.com/23580602/66254720-ee8ff300-e797-11e9-9031-0fda36d15713.png)

## TODO
- [x] Update the phone no. in the section to the one in the footer.
- [x] Add links for twitter and instagram, in this menu
- [x] Update link for twitter in footer and add instagram icon in footer.

**Comment by anu-shree** [comment]
hi want to work on second task, but no links are available in the footer.

**Comment by ankitjena** [comment]
@anu-shree Sorry for that, the twitter link is [https://twitter.com/@zairzasac](https://twitter.com/@zairzasac). The instagram link is [https://instagram.com/zairza.cetb](https://instagram.com/zairza.cetb). Also add the link and instagram icon in the footer.

**Comment by kushaggarwal** [comment]
Hello 
I would like to resolve this issue if undone

**Comment by ankitjena** [comment]
@kushaggarwal this is done
